# Module 02 Homework - Pandas
Using a dataset from _Wine Spectator_, a wine magazine, we will practice the material that we covered in notebook M02_Colab04 to M02_Colab06. This notebook will cover data transformation, grouping, and sorting using pandas.

Created by Jay Barrios Abarquez (ID: 017694040)  
Last updated: 2/20/26

In [1]:
csvurl="https://gist.githubusercontent.com/clairehq/" + \
        "79acab35be50eaf1c383948ed3fd1129/raw/407a02139ae1e134992b90b4b2b8c329b3d73a6a/winemag-data-130k-v2.csv"
import pandas as pd
wine = pd.read_csv(csvurl)

**Data cleaning**  
Notice that the first column is redundant. Part of data analysis is cleaning and removing redundancy. How would you drop the redundant column inplace, that is overwrite the dataframe.

In [2]:
### Drop the first column (which is just the index)
wine.drop(wine.columns[0], axis=1, inplace=True)
wine.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

#### Question 1: ####  
What is the mean of the points column?

In [3]:
# Your code here . . .
### Calculate the mean of the "points" column
wine["points"].mean()

88.43403716087269

#### Question 2: ####  
How many countries are present in this dataset? (Only count each country once)

In [4]:
# Your code here . . .
### Count the number of unique values in the "province" column
wine["province"].nunique()

385

#### Question 3: ####
How many times does each country appeared in this dataset? Show each country and the corresponding count (show counts in ascending order)

In [5]:
# Your code here . . .
### Count the frequency of each unique value in the "province" column
wine["province"].value_counts()

California          18122
Washington           4308
Bordeaux             3014
Tuscany              2985
Oregon               2691
                    ...
Thraki                  1
Dalmatian Coast         1
Serra do Sudeste        1
Pocerina                1
Vinho Licoroso          1
Name: province, Length: 385, dtype: int64

#### Question 4: ####
Create a variable `adjusted_price` containing the adjusted price which is the price subtracted by the average price. *This is called **"centering" transformation** - a method commonly used in the preprocessing step before applying various machine learning algorithms.*

In [7]:
# Your code here . . .
### Save the average price of the wines in a variable 
### Create a new column "adjust_price" that is equal to the price of the wine minus the average price
average_price = wine["price"].mean()
wine["adjusted_price"] = wine["price"] - average_price
wine.head() # We can see the new column at the end of the df

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,adjusted_price
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,NaN
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,-20.232932
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,-21.232932
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,-22.232932
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,29.767068

#### Question 5: ####
What is the title of the wine that has the highest points-to-price ratio in the dataset?

In [8]:
# Your code here . . .
### Create a new column "points_to_price" that is equal to the points of the wine divided by the price
### and find the max value in this new column 
### Note: To find the wine with the max, we can use the idxmax() method to get the index of the max value, 
###         and then use that index to get the wine
wine["points_to_price"] = wine["points"] / wine["price"]
max_index = wine["points_to_price"].idxmax()
wine.iloc[max_index]

country                                                                 US
description              There's a lot going on in this Merlot, which i...
designation                                                            NaN
points                                                                  86
price                                                                  4.0
province                                                        California
region_1                                                        California
region_2                                                  California Other
taster_name                                                            NaN
taster_twitter_handle                                                  NaN
title                                        Bandit NV Merlot (California)
variety                                                             Merlot
winery                                                              Bandit
adjusted_price                                                  -31.232932
points_to_price                                                       21.5
Name: 64590, dtype: object

#### Question 6: ####
Create a series `flavor_counts` that contains two values: the number of wines that has the word "tart" in the `description` column and the number of wines that has the word "berries" in the `description` column. The index of the Series should be "Tart" and "Berries" for the corresponding values.

In [12]:
# Look for the word "tart", not case sensitive, not a substring of another word.
# Same applies to the word "berries"
# Your code here . . .
### Count the number of descriptions with the word "tart"
### Note: Use regex to look for the word "tart" as a whole word, not case sensitive, and not a substring of another word
tart_counts = wine["description"].str.contains(r"\btart\b", case=False, regex=True).sum()

### Count the number of decsriptions with the word "berries"
berries_counts = wine["description"].str.contains(r"\bberries\b", case=False, regex=True).sum()

### Combine the two counts into a series
flavor_counts = pd.Series(
    [tart_counts, berries_counts],
    index=["Tart", "Berries"]
)
flavor_counts

Tart       3086
Berries    1192
dtype: int64

#### Question 7: ####
Let's convert the points into simple star ratings. A score of 90 or higher counts as 3 stars, a score of at least 80 but less than 90 is 2 stars. Any other score is 1 star.

Also, any wines from France should automatically get 3 stars, regardless of points.

Add this new column `star_ratings` to the dataframe with the number of stars for each wine in the dataset.

In [14]:
# Your code here . . .
### Main logic:
###     1. Start by giving every wine 1 star by default
###     2. Give wines with greater than 80 points 2 stars
###     3. Give wines with greater than 90 points 3 stars
###     4. Give wines with from France 3 stars
### This way, we can work our way up without having to worry about combining/missing conditions
## Step 1
wine["star_ratings"] = 1

## Step 2
wine.loc[wine["points"] > 80, "star_ratings"] = 2

## Step 3
wine.loc[wine["points"] > 90, "star_ratings"] = 3

## Step 4
wine.loc[wine["country"] == "France", "star_ratings"] = 3

## Check the df to see the new column
wine.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,adjusted_price,points_to_price,star_ratings
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,NaN,NaN,2
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,-20.232932,5.800000,2
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,-21.232932,6.214286,2
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,-22.232932,6.692308,2
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,29.767068,1.338462,2

#### Question 8: ####
Who are the most common wine reviewers in the dataset? Create a Series whose index is the taster_twitter_handle category from the dataset, and whose values count how many reviews each person wrote.

In [18]:
# Your code here . . .
### Use value_counts() to automatically make the series 
wine["taster_twitter_handle"].value_counts()

@vossroger          13045
@wineschach          7752
@kerinokeefe         5313
@paulgwine           4851
@vboone              4696
@mattkettmann        3035
@JoeCz               2605
@wawinereport        2358
@gordone_cellars     2032
@AnneInVino          1769
@laurbuzz             938
@suskostrzewa         593
@worldwineguys        465
@bkfiona               11
@winewchristina         4
Name: taster_twitter_handle, dtype: int64

#### Question 9: ####
What combination of countries and varieties are most common? Create a Series whose index is a MultiIndexof {country, variety} pairs. For example, a pinot noir produced in the US should map to {"US", "Pinot Noir"}. Sort the values in the Series in descending order based on wine count.

In [19]:
# Your code here . . .
### Use value_counts again but use two columns in the input
country_variety_counts = wine[["country", "variety"]].value_counts()
country_variety_counts

country  variety
US       Pinot Noir                  4918
         Cabernet Sauvignon          3649
         Chardonnay                  3412
France   Bordeaux-style Red Blend    2380
Italy    Red Blend                   1870
                                     ...
         Torbato                        1
         Vespaiolo                      1
         Vespolina                      1
         Vitovska                       1
Uruguay  Tempranillo-Tannat             1
Length: 1304, dtype: int64

#### Question 10 #####
Create a Series whose index is reviewers and whose values is the average score given out by that reviewer.  
*Hint:* You will need the `taster_name` and `points` columns.

In [21]:
# Your code here . . .
### Use groupby to find the each unique taster and calculate the average of their points
average_scores = wine.groupby("taster_name")["points"].mean()
average_scores

taster_name
Alexander Peartree    86.014286
Anna Lee C. Iijima    88.380506
Anne Krebiehl MW      90.587903
Carrie Dykes          86.644444
Christina Pickard     89.500000
Fiona Adams           87.090909
Jeff Jenssen          88.273504
Jim Gordon            88.604331
Joe Czerwinski        88.519770
Kerin O’Keefe         88.827969
Lauren Buzzeo         87.831557
Matt Kettmann         90.021087
Michael Schachner     86.904541
Mike DeSimone         89.030303
Paul Gregutt          89.095032
Roger Voss            88.678957
Sean P. Sullivan      88.666243
Susan Kostrzewa       86.408094
Virginie Boone        89.229557
Name: points, dtype: float64